name: gadget_shop
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Version number of the application.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons.
  cupertino_icons: ^1.0.6

  # Badges package for displaying badges in your application.
  badges: ^3.1.2
  curved_navigation_bar: ^1.0.6
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  device_preview: ^1.2.0
  riverpod: ^2.5.1
  http: ^1.2.2
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules for promoting good coding practices.
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  # Use Material Design icons.
  uses-material-design: true

  # Add assets to your project.
  assets:
    - assets/images/
    - assets/splash/
    # You can add more images or assets here, like the example below:
    # - assets/images/a_dot_ham.jpeg

  # You can also define fonts here if needed. Example format is commented below.
  # fonts:
  #

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/1.png
  android: true
  ios: true
